language: java

jdk:
- oraclejdk8
- oraclejdk11

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  # snapshots from master
  - provider: script
    skip_cleanup: true
    script: ./gradlew publish
    on:
      branch: master
      jdk: oraclejdk8
  # releases from tags
  - provider: script
    skip_cleanup: true
    script: ./gradlew publish
    on:
      tags: true
      jdk: oraclejdk8
